"""agent redesign phase 1: site configs, credentials, audit log, user roles, agent state

Revision ID: 3328e5db9060
Revises: a88b22d56945
Create Date: 2026-09-06 01:23:24.692938
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3328e5db9060'
down_revision: Union[str, None] = 'a88b22d56945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('secret_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('secret_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_credential_client_name')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_client_id'), ['client_id'], unique=False)

    op.create_table('site_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('agent', sa.JSON(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_configs_site_id'), ['site_id'], unique=True)

    with op.batch_alter_table('collectors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_version', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('os_version', sa.String(length=255), nullable=True))
        # server_default: existing rows must get a value when SQLite batch mode
        # recreates the table, otherwise the copy fails the NOT NULL constraint.
        batch_op.add_column(sa.Column('prerequisites', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('credential_versions', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('last_checkin', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_run', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('pending_actions', sa.JSON(), nullable=False, server_default='[]'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        # Existing users: enabled, and not forced to rotate (they chose their
        # password; only the env-seeded bootstrap admin gets the flag, in seed.py).
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('disabled')

    with op.batch_alter_table('collectors', schema=None) as batch_op:
        batch_op.drop_column('pending_actions')
        batch_op.drop_column('last_run')
        batch_op.drop_column('last_checkin')
        batch_op.drop_column('credential_versions')
        batch_op.drop_column('prerequisites')
        batch_op.drop_column('os_version')
        batch_op.drop_column('agent_version')

    with op.batch_alter_table('site_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_configs_site_id'))

    op.drop_table('site_configs')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_client_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
